title: linchunmian_lab's Homepage
page-top-title: linchunmian_lab
top-section-bg-text: xxx课题组
home-subtitle: linchunmian_lab&ensp;|&ensp;林椿眄课题组
copyright-text: '&copy; linchunmian_lab 2023-2025. All Rights Reserved.'
